### ISSUE TITLE
Saving scripts (to gist)

### ISSUE THREAD

**Issue by kdabir** [timroes/groovyplayground#6]
May be not on appengine (for storage quota and other reasons) but it would be good if user can create a [gist](gist.github.com) from the script and open gist for edit.

**Comment by timroes** [comment]
Sounds like a good idea. I will look into what this means (in case of login, OAuth, etc.), but I think it's a good idea.

**Comment by timroes** [comment]
Docs for the Gist create api: https://developer.github.com/v3/gists/#create-a-gist

**Comment by timroes** [comment]
implemented in e6116e93d582505035168d7dcf9a79138cf873ad

**Comment by kdabir** [comment]
that was pretty fast :)
